[input]
html_selector = "main"
base_directory = "/root/repos/joej164.github.io/docs"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "starlink-operation-at-stub-stewart-state-park.html"
url = "/starlink-operation-at-stub-stewart-state-park.html"
title = "Starlink Operation at Stub Stewart State Park"

[[input.files]]
path = "setting-up-team-viewer.html"
url = "/setting-up-team-viewer.html"
title = "Setting up Team Viewer"

[[input.files]]
path = "hagg-lake-disc-golf-course-review.html"
url = "/hagg-lake-disc-golf-course-review.html"
title = "Hagg Lake Disc Golf Course Review"

[[input.files]]
path = "starlink-operation-at-hagg-lake-disc-golf-course.html"
url = "/starlink-operation-at-hagg-lake-disc-golf-course.html"
title = "Starlink Operation at Hagg Lake Disc Golf Course"

[[input.files]]
path = "setting-up-my-search.html"
url = "/setting-up-my-search.html"
title = "Setting Up My Search"

[[input.files]]
path = "setting-up-my-blog.html"
url = "/setting-up-my-blog.html"
title = "Setting Up My Blog"

[[input.files]]
path = "why-im-doing-this-blog.html"
url = "/why-im-doing-this-blog.html"
title = "Why I'm doing this Blog"
